development:
  locales: ['cz']
  currency: 'Kč'
  long_title: 'Eshop long title'
  short_title: Eshop short
  email: 'fandisek@gmail.com'
  ga_id: xxx
  picture_style:
    square: '280x280#'
    large: '420x420>'
    original: '840x840>'

production:
  locales: ['cz']
  currency: 'Kč'
  long_title: 'Eshop long title'
  short_title: Eshop short
  email: 'fandisek@gmail.com'
  ga_id: xxx
  picture_style:
    square: '280x280#'
    large: '420x420>'
    original: '840x840>'
