development:
  locales: ['cz']
  currency: 'Kč'
  long_title: 'Ethnoshop Matahari'
  short_title: Matahari
  email: 'fandisek@gmail.com'
production:
  locales: ['cz']
  currency: 'Kč'
  long_title: 'Ethnoshop Matahari'
  short_title: Matahari
  email: 'matahari.decoration@gmail.com'
