
login: &login
  adapter: mysql2
  #socket: /var/run/mysqld/mysqld.sock
  host: localhost
  #port: 3306
  username: root
  password: maker
  timeout: 5000
  encoding: utf8

development:
  database: eshop
  <<: *login

test:
  database: eshop
  <<: *login

production:
  database: eshop
  <<: *login


