
login: &login
  adapter: postgresql
  timeout: 5000
  encoding: utf8

development:
  username: root
  password: fanda
  database: artre
  <<: *login

test:
  database: artre_test
  <<: *login

production:
  database: eshop
  <<: *login


